import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    X, ArrowRight, ArrowLeft, Sparkles, CheckCircle,
    Code, Briefcase, Award, ShieldCheck, Play, Target,
    Rocket, Star, Zap
} from 'lucide-react';

interface TourStep {
    id: string;
    title: string;
    description: string;
    icon: React.ReactNode;
    highlight?: string; // CSS selector for element to highlight
    position?: 'center' | 'top' | 'bottom' | 'left' | 'right';
    action?: string;
}

interface OnboardingTourProps {
    isOpen: boolean;
    onClose: () => void;
    onComplete: () => void;
    userRole: 'candidate' | 'employer';
}

const CANDIDATE_TOUR_STEPS: TourStep[] = [
    {
        id: 'welcome',
        title: 'Welcome to Lune! 🚀',
        description: 'Your journey to verified professional credentials starts here. Let us show you around!',
        icon: <Sparkles className="text-orange" size={32} />,
        position: 'center'
    },
    {
        id: 'skills',
        title: 'Choose Your Skills',
        description: 'Select from 50+ technical domains including Frontend, Backend, AI/ML, DevOps, and more. Pick the skills you want to get certified in.',
        icon: <Code className="text-teal" size={32} />,
        position: 'center'
    },
    {
        id: 'assessment',
        title: 'AI-Powered Assessments',
        description: 'Take custom assessments generated by AI. Each test is unique and adapts to your selected difficulty level - Beginner, Mid-Level, or Advanced.',
        icon: <Target className="text-purple-500" size={32} />,
        position: 'center'
    },
    {
        id: 'proctoring',
        title: 'Smart Proctoring',
        description: 'Our AI proctoring ensures assessment integrity through face detection, tab monitoring, and typing pattern analysis. Your verified scores mean more!',
        icon: <ShieldCheck className="text-blue-500" size={32} />,
        position: 'center'
    },
    {
        id: 'certificate',
        title: 'Blockchain Certificates',
        description: 'Pass your assessment (70%+) and mint an immutable certificate on PWRCHAIN. Share it anywhere - it\'s permanently verifiable!',
        icon: <Award className="text-orange" size={32} />,
        position: 'center'
    },
    {
        id: 'video',
        title: 'AI Video Analysis',
        description: 'Record your video introduction and get AI-powered feedback on confidence, clarity, and professionalism. Stand out to employers!',
        icon: <Play className="text-red-500" size={32} />,
        position: 'center'
    },
    {
        id: 'ready',
        title: "You're All Set! 🎉",
        description: 'Start taking assessments, build your verified profile, and connect with top employers looking for talent like you.',
        icon: <Rocket className="text-teal" size={32} />,
        position: 'center'
    }
];

const EMPLOYER_TOUR_STEPS: TourStep[] = [
    {
        id: 'welcome',
        title: 'Welcome to Lune! 🚀',
        description: 'Find verified talent with blockchain-backed credentials. Let us show you how to hire with confidence!',
        icon: <Sparkles className="text-teal" size={32} />,
        position: 'center'
    },
    {
        id: 'talent',
        title: 'Discover Verified Talent',
        description: 'Browse candidates with verified skill certifications. Filter by skill, experience, location, and certification scores.',
        icon: <Star className="text-orange" size={32} />,
        position: 'center'
    },
    {
        id: 'verify',
        title: 'Blockchain Verification',
        description: 'Each candidate\'s certification is stored on PWRCHAIN. Verify any hash instantly to confirm authentic credentials.',
        icon: <ShieldCheck className="text-teal" size={32} />,
        position: 'center'
    },
    {
        id: 'jobs',
        title: 'Post Jobs & Get Matches',
        description: 'Create job postings and let our AI match you with the best-fit candidates based on verified skills and preferences.',
        icon: <Briefcase className="text-purple-500" size={32} />,
        position: 'center'
    },
    {
        id: 'analytics',
        title: 'Enterprise Analytics',
        description: 'Access detailed hiring metrics, pipeline analytics, and team performance data to optimize your hiring process.',
        icon: <Zap className="text-blue-500" size={32} />,
        position: 'center'
    },
    {
        id: 'ready',
        title: "Ready to Hire! 🎉",
        description: 'Start exploring verified candidates or post your first job. Quality talent is just a click away!',
        icon: <Rocket className="text-teal" size={32} />,
        position: 'center'
    }
];

export const OnboardingTour: React.FC<OnboardingTourProps> = ({
    isOpen,
    onClose,
    onComplete,
    userRole
}) => {
    const [currentStep, setCurrentStep] = useState(0);
    const [isExiting, setIsExiting] = useState(false);

    const steps = userRole === 'candidate' ? CANDIDATE_TOUR_STEPS : EMPLOYER_TOUR_STEPS;
    const totalSteps = steps.length;
    const step = steps[currentStep];
    const isLastStep = currentStep === totalSteps - 1;
    const isFirstStep = currentStep === 0;

    const handleNext = useCallback(() => {
        if (isLastStep) {
            setIsExiting(true);
            setTimeout(() => {
                onComplete();
            }, 300);
        } else {
            setCurrentStep(prev => prev + 1);
        }
    }, [isLastStep, onComplete]);

    const handlePrev = useCallback(() => {
        if (!isFirstStep) {
            setCurrentStep(prev => prev - 1);
        }
    }, [isFirstStep]);

    const handleSkip = useCallback(() => {
        setIsExiting(true);
        setTimeout(() => {
            onClose();
        }, 300);
    }, [onClose]);

    // Keyboard navigation
    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (!isOpen) return;
            if (e.key === 'ArrowRight' || e.key === 'Enter') {
                handleNext();
            } else if (e.key === 'ArrowLeft') {
                handlePrev();
            } else if (e.key === 'Escape') {
                handleSkip();
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [isOpen, handleNext, handlePrev, handleSkip]);

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: isExiting ? 0 : 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4"
            >
                {/* Tour Card */}
                <motion.div
                    initial={{ scale: 0.8, opacity: 0, y: 50 }}
                    animate={{
                        scale: isExiting ? 0.8 : 1,
                        opacity: isExiting ? 0 : 1,
                        y: isExiting ? 50 : 0
                    }}
                    exit={{ scale: 0.8, opacity: 0, y: 50 }}
                    transition={{ type: 'spring', duration: 0.5 }}
                    className="relative bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden"
                >
                    {/* Progress Bar */}
                    <div className="absolute top-0 left-0 right-0 h-1 bg-gray-100">
                        <motion.div
                            className="h-full bg-gradient-to-r from-teal to-orange"
                            initial={{ width: 0 }}
                            animate={{ width: `${((currentStep + 1) / totalSteps) * 100}%` }}
                            transition={{ duration: 0.3 }}
                        />
                    </div>

                    {/* Skip Button */}
                    <button
                        onClick={handleSkip}
                        className="absolute top-4 right-4 p-2 rounded-full text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition z-10"
                    >
                        <X size={20} />
                    </button>

                    {/* Content */}
                    <div className="pt-10 pb-8 px-8">
                        {/* Step Indicator */}
                        <div className="flex justify-center gap-2 mb-6">
                            {steps.map((_, index) => (
                                <motion.div
                                    key={index}
                                    className={`h-2 rounded-full transition-all duration-300 ${index === currentStep
                                            ? 'w-8 bg-gradient-to-r from-teal to-orange'
                                            : index < currentStep
                                                ? 'w-2 bg-teal'
                                                : 'w-2 bg-gray-200'
                                        }`}
                                    whileHover={{ scale: 1.2 }}
                                />
                            ))}
                        </div>

                        {/* Step Content - Animated */}
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={step.id}
                                initial={{ opacity: 0, x: 50 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -50 }}
                                transition={{ duration: 0.3 }}
                                className="text-center"
                            >
                                {/* Icon */}
                                <motion.div
                                    initial={{ scale: 0, rotate: -180 }}
                                    animate={{ scale: 1, rotate: 0 }}
                                    transition={{
                                        type: 'spring',
                                        stiffness: 200,
                                        delay: 0.1
                                    }}
                                    className="w-20 h-20 mx-auto mb-6 bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl flex items-center justify-center shadow-lg"
                                >
                                    {step.icon}
                                </motion.div>

                                {/* Title */}
                                <motion.h2
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: 0.15 }}
                                    className="text-2xl font-bold text-slate-900 mb-3"
                                >
                                    {step.title}
                                </motion.h2>

                                {/* Description */}
                                <motion.p
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: 0.2 }}
                                    className="text-gray-600 leading-relaxed"
                                >
                                    {step.description}
                                </motion.p>
                            </motion.div>
                        </AnimatePresence>
                    </div>

                    {/* Navigation */}
                    <div className="px-8 pb-8 flex items-center justify-between">
                        {/* Back Button */}
                        <motion.button
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            onClick={handlePrev}
                            disabled={isFirstStep}
                            className={`flex items-center gap-2 px-4 py-2 rounded-xl font-medium transition ${isFirstStep
                                    ? 'text-gray-300 cursor-not-allowed'
                                    : 'text-gray-600 hover:bg-gray-100'
                                }`}
                        >
                            <ArrowLeft size={18} />
                            Back
                        </motion.button>

                        {/* Step Counter */}
                        <span className="text-sm text-gray-400">
                            {currentStep + 1} of {totalSteps}
                        </span>

                        {/* Next/Complete Button */}
                        <motion.button
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            onClick={handleNext}
                            className={`flex items-center gap-2 px-6 py-2.5 rounded-xl font-semibold transition shadow-lg ${isLastStep
                                    ? 'bg-gradient-to-r from-teal to-darkblue text-white hover:shadow-xl hover:shadow-teal/30'
                                    : 'bg-black text-white hover:bg-gray-800'
                                }`}
                        >
                            {isLastStep ? (
                                <>
                                    <CheckCircle size={18} />
                                    Get Started
                                </>
                            ) : (
                                <>
                                    Next
                                    <ArrowRight size={18} />
                                </>
                            )}
                        </motion.button>
                    </div>

                    {/* Decorative Elements */}
                    <div className="absolute -bottom-20 -right-20 w-40 h-40 bg-gradient-to-br from-teal/10 to-orange/10 rounded-full blur-3xl pointer-events-none" />
                    <div className="absolute -top-20 -left-20 w-40 h-40 bg-gradient-to-br from-orange/10 to-teal/10 rounded-full blur-3xl pointer-events-none" />
                </motion.div>

                {/* Keyboard Hint */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 0.6, y: 0 }}
                    transition={{ delay: 1 }}
                    className="absolute bottom-8 left-1/2 -translate-x-1/2 flex items-center gap-4 text-white/80 text-sm"
                >
                    <span className="flex items-center gap-1">
                        <kbd className="px-2 py-1 bg-white/20 rounded text-xs">←</kbd>
                        <kbd className="px-2 py-1 bg-white/20 rounded text-xs">→</kbd>
                        Navigate
                    </span>
                    <span className="flex items-center gap-1">
                        <kbd className="px-2 py-1 bg-white/20 rounded text-xs">Enter</kbd>
                        Continue
                    </span>
                    <span className="flex items-center gap-1">
                        <kbd className="px-2 py-1 bg-white/20 rounded text-xs">Esc</kbd>
                        Skip
                    </span>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
};

// Onboarding Progress Component for multi-step forms
interface OnboardingProgressProps {
    steps: string[];
    currentStep: number;
    className?: string;
}

export const OnboardingProgress: React.FC<OnboardingProgressProps> = ({
    steps,
    currentStep,
    className = ''
}) => {
    return (
        <div className={`flex items-center justify-center gap-2 ${className}`}>
            {steps.map((step, index) => (
                <React.Fragment key={step}>
                    {/* Step Circle */}
                    <div className="flex flex-col items-center">
                        <motion.div
                            initial={false}
                            animate={{
                                scale: index === currentStep ? 1.2 : 1,
                                backgroundColor: index <= currentStep ? '#0A9396' : '#E5E7EB'
                            }}
                            className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors ${index <= currentStep ? 'text-white' : 'text-gray-400'
                                }`}
                        >
                            {index < currentStep ? (
                                <CheckCircle size={16} />
                            ) : (
                                index + 1
                            )}
                        </motion.div>
                        <span className={`text-xs mt-1 font-medium ${index === currentStep ? 'text-teal' : 'text-gray-400'
                            }`}>
                            {step}
                        </span>
                    </div>

                    {/* Connector Line */}
                    {index < steps.length - 1 && (
                        <div className="w-12 h-0.5 bg-gray-200 relative -mt-4">
                            <motion.div
                                initial={false}
                                animate={{
                                    width: index < currentStep ? '100%' : '0%'
                                }}
                                className="absolute inset-0 bg-teal"
                                transition={{ duration: 0.3 }}
                            />
                        </div>
                    )}
                </React.Fragment>
            ))}
        </div>
    );
};

// Tooltip Component for contextual help
interface TooltipProps {
    content: string;
    children: React.ReactNode;
    position?: 'top' | 'bottom' | 'left' | 'right';
}

export const Tooltip: React.FC<TooltipProps> = ({
    content,
    children,
    position = 'top'
}) => {
    const [isVisible, setIsVisible] = useState(false);

    const positionClasses = {
        top: 'bottom-full left-1/2 -translate-x-1/2 mb-2',
        bottom: 'top-full left-1/2 -translate-x-1/2 mt-2',
        left: 'right-full top-1/2 -translate-y-1/2 mr-2',
        right: 'left-full top-1/2 -translate-y-1/2 ml-2'
    };

    const arrowClasses = {
        top: 'top-full left-1/2 -translate-x-1/2 border-t-gray-900',
        bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-gray-900',
        left: 'left-full top-1/2 -translate-y-1/2 border-l-gray-900',
        right: 'right-full top-1/2 -translate-y-1/2 border-r-gray-900'
    };

    return (
        <div
            className="relative inline-block"
            onMouseEnter={() => setIsVisible(true)}
            onMouseLeave={() => setIsVisible(false)}
        >
            {children}
            <AnimatePresence>
                {isVisible && (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.9 }}
                        className={`absolute z-50 ${positionClasses[position]}`}
                    >
                        <div className="bg-gray-900 text-white text-sm px-3 py-2 rounded-lg shadow-lg max-w-xs whitespace-nowrap">
                            {content}
                        </div>
                        <div className={`absolute w-0 h-0 border-4 border-transparent ${arrowClasses[position]}`} />
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

// Feature Highlight for first-time feature discovery
interface FeatureHighlightProps {
    title: string;
    description: string;
    isNew?: boolean;
    onDismiss: () => void;
    children: React.ReactNode;
}

export const FeatureHighlight: React.FC<FeatureHighlightProps> = ({
    title,
    description,
    isNew = true,
    onDismiss,
    children
}) => {
    const [isVisible, setIsVisible] = useState(true);

    if (!isVisible) return <>{children}</>;

    return (
        <div className="relative">
            {children}

            {/* Highlight Overlay */}
            <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="absolute -inset-2 rounded-2xl ring-2 ring-teal ring-offset-2 ring-offset-white pointer-events-none"
            />

            {/* Tooltip */}
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="absolute top-full left-1/2 -translate-x-1/2 mt-4 w-64 bg-gray-900 text-white p-4 rounded-xl shadow-xl z-50"
            >
                <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                        {isNew && (
                            <span className="px-2 py-0.5 bg-orange text-xs font-bold rounded-full">
                                NEW
                            </span>
                        )}
                        <h4 className="font-bold">{title}</h4>
                    </div>
                    <button
                        onClick={() => {
                            setIsVisible(false);
                            onDismiss();
                        }}
                        className="text-gray-400 hover:text-white"
                    >
                        <X size={16} />
                    </button>
                </div>
                <p className="text-sm text-gray-300">{description}</p>

                {/* Arrow */}
                <div className="absolute -top-2 left-1/2 -translate-x-1/2 w-4 h-4 bg-gray-900 rotate-45" />
            </motion.div>
        </div>
    );
};

export default OnboardingTour;
